[project]
name = "cowmcpservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.6"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.27.2",
    "fastmcp==3.2.0",
    "aiohttp==3.14.3",
    "h11==0.16.0",
    "urllib3>=2.6.0",
    "python-multipart==0.0.32",
    "starlette>=0.49.1",
    "pandas==2.3.1",
    "PyYAML==6.0.2",
    "toml>=0.10.2",
    "ruamel.yaml==0.18.14",
    "requests==2.32.4",
    "django==6.0.4",
    "cachetools==6.2.1",
    "uvicorn[standard]==0.38.0",
    "toon-format",
    "sqlparse==0.6.0",
    "cryptography==50.0.0",
    "croniter==6.2.4",
    "cron-descriptor==2.1.0",
]
[tool.setuptools.packages.find]
where = ["."]
include = ["tools*", "utils*", "mcpconfig*", "constants*", "resources*"]

[tool.uv.sources]
toon-format = { git = "https://github.com/toon-format/toon-python.git" }

